### ISSUE TITLE
T2med-Version 24.8.0 - keine Patientensuche in T2med

### ISSUE THREAD

**Issue by stavismed** [INT3hex/TAPICallerID#1]
Die Idee finde ich super. Wenigstens eine kleine Möglichkeit um T2med in irgendeiner Form von extern zu bedienen.
Danke schon mal dafür.

Ich habe das ganze installiert. Das TrayIcon blinkt auch schön, wenn ich anrufe und nimmt die Nummer auf.
Wenn ich dann allerdings mit Rechs-Klick auf das Icon "Letzter Anruf" gehe, dort steht meine Telefonnummer mit "~0176xxx20"-Prefix.
Ich klicke auf "Zu T2med", dann geht der Fokus zur T2med-App, aber es wird nicht der Patient gesucht.
T2med bleibt einfach auf der Seite wo es war.
Die Nummer steht im verknüpften csv drin (als "0176xxx20")
Funktioniert die Schnittstelle noch mit der Version 24.8.0?

**Comment by INT3hex** [comment]
@stavismed Danke für das Feedback! 

längere Antwort:
leider ist die Herausforderung in T2med, dass die GUI nicht deterministisch angesprochen werden kann, d.h. die GUI-Controls haben z.B. keinen Bezeichner/Namen, sondern bekommen bei jedem T2med-Start jeweils dynamische IDs. Daher muss das Such-Eingabefeld von T2med ermittelt werden. (erfolgt hier: https://github.com/INT3hex/TAPICallerID/blob/master/TrayApp/WindowHandling.vb)

In der Version 1.1 hatte ich das Verfahren nochmals angepasst, was sich jedoch als abhängig von der Bildschirmauflösung zeigt.
Der Parameter, mit dem Du das steuern kannst, wäre "wndT2SearchControlHeight" value="53" - allerdings ist ohne Debuginformation das Herausfinden des richtigen Werts schwierig (d.h. Trial&Error)
Bei den Praxissystemen ist bei uns der Wert **66**  

Aus einer Diskusssion im T2med-Forum hatte ich mitgenommen, dass 3rd Party-Programme (z.B. Praxisconcierge) über den (Um-)Weg GDT-Anbindung eine Kalenderanbindung und Sprung in die Patientenakte realisieren. Dies wollte ich in einer Folgeversion ebenfalls mal implementieren.

Wir sind seit dem WoE wieder aus dem Urlaub zurück und ich würde diese Woche mich mal etwas in die GDT-Schnittstelle einarbeiten, d.h. wenn noch etwas Geduld besteht, dann wäre ggf. nächste Woche eine neue Version, die ohne GUI-Gefummel auskommt verfügbar.

kurze Antwort:
ja, funktioniert auch mit T2med 24.8.0, es muss aber der richtige Wert für "wndT2SearchControlHeight" in die .config eingetragen werden. Oder ggf. auf das ältere Release (https://github.com/INT3hex/TAPICallerID/releases/tag/v1.0d) zurückgreifen.

Grüße
Alex

**Comment by stavismed** [comment]
Hallo Alex,
danke für die Erläuterung. Ich dachte es wäre tatsächlich eine Art "echte" Schnittstelle mit T2med.
Das Search-Window-Finden-Ding hatte ich auch schon probiert, bin aber tatsächlich gescheitert, weil - wie du sagst, das GUI ziemlich dynamisch aufgebaut wird.

Ich habe das jetzt mit der GDT-Schnittstelle ausprobiert (auch etwas fummelig).
Aber damit du noch deine Urlaubsentspannung etwas genießen kann, habe ich mal etwas Vorarbeit gemacht. 
Vielleicht kannst du etwas davon nutzen.

In T2med habe ich über "Geräte verwalten" folgendes "Gerät" angelegt:
![image](https://github.com/user-attachments/assets/25facd36-981c-484c-9a7a-9168bbe6ed9d)

Und unter "Übernahme von Befunden" folgendes eingetragen:
![image](https://github.com/user-attachments/assets/eae3b8c3-b66d-4b21-b4ab-9caf5764e423)

(Ich bin mir nicht sicher, ob alle Einträge Sinn machen - der "Dateiname Export" ist wahrscheinlich sinnlos)

Wenn ich jetzt in das Verzeichnis C:\tmp\gdtexport
eine Datei EXPOTER.GDT lege, mit folgendem Inhalt:

```
01380006301
014810000124
0178315PRAX_EDV
0178316TERMINP1
014921802.10
01092063
0103000331
01031101
```

springt T2med nahezu sofort zum Patienten mit der ID 331 (vorletzte Zeile mit Prefix "0103000") und löscht dann die Datei.
Auch hier weiß ich nicht wie viel von der Datei nötig ist. Aber zumindest funktioniert es bei mir so.

**Comment by INT3hex** [comment]
@stavismed WOW - Besten Dank für die Vorarbeit, die ja quasi schon die fertige Arbeit ist (-:

Ich war gerade auch nicht ganz untätig und habe noch einen kleinen Patch für die "Suchfeldsuche" gemacht...
https://github.com/INT3hex/TAPICallerID/releases/tag/v1.1.2
Das ist nun eine kleine Vereinfachung der Suche, damit sollte aber bei Dir der Einsprung in das Suchfeld funktionieren... 
(Kurze Rückmeldung ob es funktioniert wäre nett.)

Die GDT-Anbindung folgt...

**Comment by INT3hex** [comment]
@stavismed GDT ist mit v1.2 implementiert. ;-)

**Comment by stavismed** [comment]
@INT3hex ... na, DAS ist mal ein Tempo nach dem Urlaub. So schnell kann ich gar nicht testen.

Der Reihe nach:
wndT2SearchControlHeight=66 hat dann auch bei mir funktioniert. 👍

Die GDT-Schnittstelle mit Version 1.2 ist aber natürlich wesentlich schöner und funktioniert prima.
Vielleicht könntest du noch im Readme erwähnen, dass der Key für den Pfad zur GDT-Datei in "sGDTFile" konfiguriert wird (ich hab's mir aus dem Code rausgesucht).
Edit: Im Beispiel-Config ist es ja genannt (wer lesen kann ...)

Und nach Einrichten der GDT-Schnittstelle in T2med muss man sich einmal neu anmelden. Eigentlich wusste ich das ja ... aber ... rate 🤷‍♂️

**Comment by INT3hex** [comment]
Hallo stavismed,

na, Dank Deiner Vorarbeit und ein wenig noch GDT-Spezifikation lesen, ging's schnell ;-)

ja wg. **sGDTFile**, genau, ist eigentlich unter _Erweiterungen mit Version 1.2_ und in der Beispielkonfig genannt.
Die App würde aber auch die Defaultkonfiguration in der Konfig ergänzen, wenn man einmal die GDT-Nutzung aktiviert hat. Würde dann ggf. noch in einen Fehler laufen, da das Verzeichnis nicht stimmt, aber man könnte dann in der Konfig den Pfad anpassen. Ich versuche eigentlich immer die Konfigurationsoptionen zumindest mit Defaultwerten vorzubelegen...

jupp, in T2Med muss nach Einrichten der GDT-Schnittstelle zumindest ab/neuangemeldet oder neu gestartet werden.
Das ergänze ich ggf. noch im T2Med-Forum - hier hatte ich auch noch kleine Snippets für Powershell und LibreOffice Basic zur Anbindung der GDT-Schnittstelle gepostet.

Gruß
Alex
